apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
  labels:
    run: app
spec:
  replicas: 2
  selector:
    matchLabels:
      run: app
  template:
    metadata:
      labels:
        run: app
    spec:
      containers: 
      - name: app
        image: asia.gcr.io/fit-ietochi/simple-app
        resources:
          limits:
            cpu: 0.5
            memory: 300Mi
          requests:
            cpu: 0.1
            memory: 20Mi
        ports:
          - containerPort: 8080
        env:
          - name: DB_HOST
            value: 10.32.0.3:3306
          - name: DB_DBNAME
            value: fit-development
          - name: DB_USERNAME
            valueFrom:
              secretKeyRef:
                name: db-secret
                key: username
          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: db-secret
                key: password
