apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: db-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      run: db
  template:
    metadata:
      labels:
        run: db
    spec:
      containers:
        - name: cloudsql-proxy
          image: gcr.io/cloudsql-docker/gce-proxy:1.16
          command: ["/cloud_sql_proxy",
                    "-instances=fit-ietochi:asia-northeast2:fit-46c4=tcp:3306",
                    "-credential_file=/secrets/cloudsql/credentials.json"]
          volumeMounts:
            - name: db-secret
              mountPath: /secrets/cloudsql
              readOnly: true
      volumes:
        - name: db-secret
          secret:
            secretName: db-secret
