steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'asia.gcr.io/lp-test-263613/k8s-test-app:$REVISION_ID', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'asia.gcr.io/lp-test-263613/k8s-test-app:$REVISION_ID']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'asia.gcr.io/lp-test-263613/k8s-test-app:latest']
- name: 'gcr.io/cloud-builders/kubectl'
  args:
  - set
  - image
  - deployment/app
  - app=asia.gcr.io/lp-test-263613/k8s-test-app:$REVISION_ID
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=asia-northeast1-a'
  - 'CLOUDSDK_CONTAINER_CLUSTER=standard-cluster-1'
