steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'asia.gcr.io/fit-ietochi/simple-app:$REVISION_ID', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'asia.gcr.io/fit-ietochi/simple-app:$REVISION_ID']
- name: 'gcr.io/cloud-builders/kubectl'
  args:
  - set
  - image
  - deployment/app
  - app=asia.gcr.io/fit-ietochi/simple-app:$REVISION_ID
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=asia-northeast2-a'
  - 'CLOUDSDK_CONTAINER_CLUSTER=fit-main'
