steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'asia.gcr.io/lp-test-263613/k8s-test-app:$REVISION_ID', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['tag', 'asia.gcr.io/lp-test-263613/k8s-test-app:$REVISION_ID', 'asia.gcr.io/lp-test-263613/k8s-test-app:latest']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'asia.gcr.io/lp-test-263613/k8s-test-app:$REVISION_ID']
