apiVersion: apps/v1
kind: Deployment
metadata:
  name: db
  labels:
    run: db
spec:
  replicas: 1
  selector:
    matchLabels:
      run: db
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        run: db
    spec:
      containers: 
      - name: db
        image: mysql:5.7
        imagePullPolicy: IfNotPresent
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: password
        ports:
        - containerPort: 3306
